# -*- coding: utf-8 -*-
"""khushboo.project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcOLGNcWfbJngdzEmArJJCPlasZfYmKa

**Load and Inspect Dataset**
"""

import pandas as pd

# Load dataset
df = pd.read_csv("./HHS_Unaccompanied_Alien_Children_Program.csv")

# Display first 5 rows
print(df.head())

# Basic info
print(df.info())

# Summary statistics
print(df.describe())

# Convert 'Date' to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Remove commas and convert to numeric
df['Children in HHS Care'] = df['Children in HHS Care'].str.replace(',', '').astype(float)

# Check missing values
print(df.isnull().sum())

"""**Find Total, Mean, Max, Min**"""

print("Total Children in CBP custody:", df['Children in CBP custody'].sum())
print("Average Children in HHS Care:", df['Children in HHS Care'].mean())
print("Maximum Children apprehended:", df['Children apprehended and placed in CBP custody*'].max())
print("Minimum Children discharged:", df['Children discharged from HHS Care'].min())

"""**Time Series Analysis**"""

# Sort by date
df = df.sort_values('Date')

# Plot trend
import matplotlib.pyplot as plt

plt.plot(df['Date'], df['Children in HHS Care'])
plt.xlabel("Date")
plt.ylabel("Children in HHS Care")
plt.title("Trend of Children in HHS Care Over Time")
plt.xticks(rotation=45)
plt.show()

"""**Correlation Analysis**"""

# Correlation matrix
correlation = df.corr(numeric_only=True)
print(correlation)

"""**Highest and Lowest Records**"""

# Highest CBP custody
print(df.loc[df['Children in CBP custody'].idxmax()])

# Lowest CBP custody
print(df.loc[df['Children in CBP custody'].idxmin()])

"""**Grouping (Monthly Analysis)**"""

# Extract month
df['Month'] = df['Date'].dt.month

# Group by month
monthly_avg = df.groupby('Month')['Children in HHS Care'].mean()
print(monthly_avg)

"""**Visualization (Bar Chart)**"""

df.head(10).plot(x='Date', y='Children in CBP custody', kind='bar')
plt.title("CBP Custody (Sample Data)")
plt.xticks(rotation=45)
plt.show()

"""**Detect Trends (Increase/Decrease)**"""

df['Change'] = df['Children in HHS Care'].diff()

print(df[['Date', 'Children in HHS Care', 'Change']])

"""**Export Cleaned Data**"""

df.to_csv("cleaned_dataset.csv", index=False)
